# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  cpptests:
    docker:
      - image: gcc:latest
    working_directory: ~/circleci-googletest
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - run:
          name: Install Dependencies
          command: |
            apt-get -y -q update
            apt-get -y -q install cmake gcc libomp-dev libeigen3-dev
      - run:
          name: Install Google Test
          working_directory: ~/googletest
          command: |
            wget -qO - https://github.com/google/googletest/archive/release-1.8.1.tar.gz | tar -xz
            cmake -D CMAKE_INSTALL_PREFIX:PATH=$HOME/googletest -D CMAKE_BUILD_TYPE=Release googletest-release-1.8.1
            make install
      - checkout
      - run:
          name: Build unit tests
          command: |
            cd tests
            GOOGLETEST_DIR=/root/googletest make cpptests
      - run:
          name: Run unit tests
          command: |
            cd tests && ./cpptests

  pythoncoverage:
    docker:
      - image: circleci/python:3.6.8-stretch
    working_directory: ~/tests
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            sudo apt-get -qq update;
            sudo apt-get install -y gcc libeigen3-dev;
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install pytest pytest-cov wheel codecov
            pip install -e .
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make coverage
      - codecov/upload:
          file: coverage.xml


  linux-wheels:
    working_directory: ~/linux-wheels
    docker:
      - image: circleci/python:3.6.8-stretch
    environment:
      CIBW_SKIP: "cp27-* cp34-* *i686"
      CIBW_BEFORE_BUILD_LINUX: curl -OsL https://bitbucket.org/eigen/eigen/get/3.3.7.tar.gz && tar xzf 3.3.7.tar.gz eigen-eigen-323c052e1731/Eigen --strip-components 1 && cp -rf Eigen {project}/include && pip install numpy scipy cython
      CIBW_TEST_REQUIRES: numpy scipy pytest pytest-cov
      CIBW_TEST_COMMAND: python -m pytest {project}/thewalrus
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build the Linux wheels.
          command: |
            pip install --user cibuildwheel==0.10.2
            python -m cibuildwheel --output-dir wheelhouse
      - run:
          name: Upload Linux wheels.
          filters:
            branches:
              only: master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "Uploading wheels..."
              pip install --user https://github.com/joerick/libcloud/archive/v1.5.0-s3fix.zip wheelhouse-uploader
              python -m wheelhouse_uploader upload --provider-name S3 --local-folder wheelhouse/ xanadu-wheels
            else
              echo "Not on master, not deploying."
            fi
      - store_artifacts:
          path: wheelhouse/

  osx-wheels:
    working_directory: ~/osx-wheels
    macos:
      xcode: "10.0.0"
    environment:
      CIBW_SKIP: "cp27-* cp34-* *i686"
      CIBW_BEFORE_BUILD_MACOS: brew cask uninstall --force oclint && brew install gcc eigen libomp || true; brew install gcc eigen libomp && pip install numpy scipy cython
      CIBW_TEST_REQUIRES: numpy scipy pytest pytest-cov
      CIBW_TEST_COMMAND: python -m pytest {project}/thewalrus
    steps:
      - checkout
      - run:
          name: Build the OS X wheels.
          command: |
            pip install --user cibuildwheel
            export PATH=$PATH:/Users/distiller/Library/Python/2.7/bin
            cibuildwheel --output-dir wheelhouse
      - run:
          name: Upload OS X wheels.
          filters:
            branches:
              only: master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "Uploading wheels..."
              pip install --user https://github.com/joerick/libcloud/archive/v1.5.0-s3fix.zip wheelhouse-uploader
              python -m wheelhouse_uploader upload --provider-name S3 --local-folder wheelhouse/ xanadu-wheels
            else
              echo "Not on master, not deploying."
            fi
      - store_artifacts:
          path: wheelhouse/

workflows:
  version: 2
  all-tests:
    jobs:
      - cpptests
      - linux-wheels
      - osx-wheels
